---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the Python interpreter
#
########################################################################

- name: Python is installed
  block:

  - name: Look for python3 or python binaries
    ansible.builtin.raw: >
      which python3 2>/dev/null ||
      command -v python3 ||
      which python 2>/dev/null ||
      command -v python
    register: discover_python_reg
    changed_when: false

  - name: The Python interpreter is already configured
    block:

    - name: "{{ansible_python_interpreter}} is valid"
      ansible.builtin.raw: "{{ansible_python_interpreter}} --version"
      changed_when: false

    rescue:

    - name: "Set Python interpreter to {{python_interpreter_var}}"
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{python_interpreter_var}}"
      changed_when: true
      notify: save host vars
      vars:
        python_interpreter_var: "{{discover_python_reg['stdout_lines'][0]}}"

  rescue:

  - name: Install Python
    ansible.builtin.include_tasks: install_python.yml
