---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Create ansible user
#
########################################################################

- name: Create ansible user
  ansible.builtin.user:
    name: "{{ new_user_var }}"
    password_lock: true
  register: user_changed
  become: true
