---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Setup host
#
########################################################################

- name: "Configure connection to {{inventory_hostname}}"
  ansible.builtin.include_tasks: cfg_con.yml

- name: Configure privilege escalation (become method)
  ansible.builtin.include_tasks: cfg_become.yml
  when: ansible_user != 'root'

- name: Get platform
  ansible.builtin.raw: uname
  register: uname_reg
  changed_when: false

- name: Install macOS Dependencies
  block:

  - name: Gather facts
    ansible.builtin.setup:

  - name: Install command line tools
    ansible.builtin.include_role:
      name: elliotweiser.osx-command-line-tools

  - name: Install Homebrew
    ansible.builtin.include_role:
      name: geerlingguy.mac.homebrew

  when: uname_reg['stdout_lines'][0] | lower == 'darwin'

- name: Configure Python interpreter
  ansible.builtin.include_tasks: cfg_python.yml

- name: Gather facts
  ansible.builtin.setup:

- name: Load platform-specific variables
  ansible.builtin.include_tasks: vars.yml

- name: Install any other Ansible dependencies (except on macOS)
  ansible.builtin.package:
    name: "{{ansible_dependencies}}"
    state: present
  become: true
  when: ansible_system | lower != 'darwin'

- name: Install any other Ansible dependencies (macOS)
  community.general.homebrew:
    name: "{{ansible_dependencies}}"
    state: installed
  when: ansible_system | lower == 'darwin'

- name: Configure SELinux
  ansible.builtin.include_tasks: cfg_selinux.yml

- name: "Set timezone to {{site['tz']}} on {{inventory_hostname}}"
  community.general.timezone:
    name: "{{site['tz']}}"
  become: true
