---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure networking on the host. This is executed in serial to avoid
# IP address collisions.
#
########################################################################

- name: Configure host networks in serial
  when: inventory_hostname == host_item
  block:

  - name: Configure interfaces
    ansible.builtin.include_tasks: cfg_iface.yml
    loop: "{{ phy_ifaces | default([]) }}"
    loop_control:
      loop_var: phy_iface_item

  - name: Configure bridges
    ansible.builtin.include_tasks: cfg_bridge.yml
    when: bridge_item is defined
    loop: "{{ phy_ifaces
              | default([])
              | selectattr('bridge', 'defined')
              | map(attribute='bridge')
              | unique }}"
    loop_control:
      loop_var: bridge_item
