---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the network control service on Linux. Only NetworkManager
# and networkd are supported. Which service to use is determined in
# def_net_ctl_srv_linux.yml.
#
########################################################################

- name: Configure the network control service on Linux
  ansible.builtin.include_tasks: "cfg_net_ctl_srv_linux_{{ net_ctl_srv }}.yml"

# ifupdown is not supported. Must be disabled after network restart
# handlers run to avoid losing connection to hosts.
- name: Stop and disable networking.service
  ansible.builtin.service:
    name: networking.service
    state: stopped
    enabled: false
  become: true
  vars:
    ifupdown_status_var: "{{  services['networking.service']['status']
                              | default('not-found') }}"
  when: ifupdown_status_var != 'not-found'
  notify: update service facts
