---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible:noai
#
# Configure a network bridge
#
########################################################################

- name: Define the bridge name
  ansible.builtin.set_fact:
    bridge_dev: "{{ 'bridge' +  site_subnets[bridge_net_item]['subnet_id']
                                | string }}"

- name: "Add physical interface members to bridge {{ bridge_dev }}"
  ansible.builtin.set_fact:
    bridge_members: "{{ bridge_members
                        | default([])
                        | union( [dev_item] ) }}"
  loop: "{{ phy_ifaces
            | selectattr('bridge', 'defined')
            | selectattr('bridge', '==', bridge_net_item)
            | map(attribute='dev') }}"
  loop_control:
    loop_var: dev_item

# If VLAN on the same subnet is configured on the host, bridge to it.
- name: "Add {{ bridge_vlan_var }} to bridge {{ bridge_dev }}"
  ansible.builtin.set_fact:
    bridge_members: "{{ bridge_members
                        | union([bridge_vlan_var]) }}"
  vars:
    bridge_vlan_var: "{{  'vlan'
                          +  site_subnets[bridge_net_item]['subnet_id']
                             | string }}"
  when: bridge_net_item in phy_iface_item['vlans'] | default([])
  loop: "{{ phy_ifaces }}"
  loop_control:
    loop_var: phy_iface_item

# Configure the bridge. Currently only supported on OpenBSD.
- name: Run platform-specific bridge configuration tasks
  ansible.builtin.include_tasks: "{{ lookup('first_found', files_var) }}"
  vars:
    prefix_var: cfg_bridge_
    files_var:
      files:
        - "{{ prefix_var }}\
          {{ ansible_distribution | lower }}-\
          {{ ansible_distribution_version | lower }}_\
          {{ net_ctl_srv | default }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_distribution | lower }}-\
          {{ ansible_distribution_version | lower }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_distribution | lower }}-\
          {{ ansible_distribution_major_version | default('') | lower }}_\
          {{ net_ctl_srv | default }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_distribution | lower }}-\
          {{ ansible_distribution_major_version | default('') | lower }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_distribution | lower }}_\
          {{ net_ctl_srv | default }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_distribution | lower }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_os_family | lower }}_\
          {{ net_ctl_srv | default }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_os_family | lower }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_system | lower }}_\
          {{ net_ctl_srv | default }}.yml"
        - "{{ prefix_var }}\
          {{ ansible_system | lower }}.yml"
      paths:
        - tasks/
