---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Define all discovered physical interfaces (macOS)
#
# Use system_profiler to gather hardware MAC addresses and device names.
#
########################################################################

- name: Get network information on macOS using system_profiler
  ansible.builtin.command:
    argv:
      - system_profiler
      - -json
      - SPNetworkDataType
  changed_when: false
  register: system_profiler_network_reg

- name: Define a list of hardware interface dictionaries
  ansible.builtin.set_fact:
    phy_ifaces_disco: >-
      {{ phy_ifaces_disco
         | default([])
         | union( [ { 'dev': prof_item['interface'],
                      'hw_addr': prof_item['Ethernet']['MAC Address'] } ] ) }}
  vars:
    sp_json_var: "{{ system_profiler_network_reg['stdout'] | from_json }}"
  when: prof_item['Ethernet']['MAC Address'] is defined
  loop: "{{ sp_json_var['SPNetworkDataType']
            | selectattr('Ethernet', 'defined') }}"
  loop_control:
    loop_var: prof_item
